### ISSUE TITLE
No sniffing, only hopping between channels

### ISSUE THREAD

**Issue by eranlambooij** [Informatic/esp8266-sniffer#3]
Dear,

I tried to compile and run the code on my esp8266 12-e using SDK1.5.2 and it compiled and runs. The only problem is it does not sniff any packets. It hops around the channels fine, but it does not sniff anything. I tried to use 1.5.0, but that did not work as well. Did you use any particular SDK version?

**Comment by Informatic** [comment]
Hi, i remember i did it on one of first SDKs (well, first working commit is >1 year ago) - you'd have to do some googling, since i don't really remember which version that was. I remember being able to fix it for some recent SDK without much problem, but i don't think i can dig it up from my backups right now. Sorry.

**Comment by eranlambooij** [comment]
Hi, yeah I guessed that, but thought that it would be nice to know on which SDK it worked. I have dug into the header files/code and cannot find anything suspicious. The biggest problem is that I do not know how to debug this, since I have the feeling the callback is never called. I also do not get any errors or resets. 

I have tried to google (I always search before I ask) and could not find anything that works on one of the newer SDK's. I know I could just use an older SDK, but would like to tackle this now I started working on it, so others will benefit from it as well :)

**Comment by eranlambooij** [comment]
Hi I finally got it working. The problem was that `wifi_promiscuous_enable` should be written outside of the `user_init` function in the new SDK. If you do that it is kind of straightforward. Do you want me to make a patch?

**Comment by mrchriswanderson** [comment]
When you say outside of user_int what does that mean?  Could you post the code?

**Comment by Informatic** [comment]
Hi all, I've published rewritten sniffing app based on Sming framework (not very tight requirement, though, so you should be able to rip it out and use plain SDK quite easily) - it now supports special frames with "RxControl" header for some packets (when packet length is reported to be 128 bytes) which contains interesting information such as RSSI.

https://github.com/Informatic/Sming_WiFi_Monitor
